Helper function creation and its use in test cases.
webaccess/crmplatform pull request #51
Opened 2020-05-11 06:39 UTC by Ankitashinde0

2020-05-12 17:44 UTC, kurund requested changes

2020-05-12 17:44 UTC, kurund commented on controllers/common/base.js
> +    console.log("table---", table);
Please remove unnecessary console.log()

2020-05-12 17:44 UTC, kurund commented on tests/integration/utils/getId.js
> +const data = require("../config/config");
We should not create a separate file for each function. Can you move this to tests/integration/utils.js

2020-05-14 06:01 UTC, tanviGanesh commented on tests/integration/config/config.js.sample
>  module.exports = {
why 2 declarations for module.exports required?

2020-05-18 06:11 UTC, closed without merging